feat(tooltip): manual testing
scania-digital-design-system/tegel-react-demo pull request #101
Opened 2023-07-03 12:49 UTC by nathalielindqvist

Added test for the Tooltip component.

2023-07-03 14:22 UTC, mJarsater commented on src/pages/FormPage.tsx
> +              <div slot="label" id="anonymously">Answer anonymously
I would suggest targeting this with CSS and setting:

display: flex;
align-items: center;
gap: 4px;

and then remove the inline styling on the icon.

2023-07-05 07:38 UTC, alexandereneroth requested changes
The 'show' prop needs testing too
https://tegel-storybook.netlify.app/?path=/info/components--tooltip

2023-07-05 08:22 UTC, nathalielindqvist commented
> The 'show' prop needs testing too https://tegel-storybook.netlify.app/?path=/info/components--tooltip

Great stuff, updated now! 😄

2023-07-05 08:58 UTC, alexandereneroth commented
Hmm seems like the 'show' prop only shows it initially - if you hover in and out of it it closes. 
I don't think thats expected behavior, prolly needs a ticket

2023-07-05 08:58 UTC, alexandereneroth approved these changes

2023-07-05 08:59 UTC, nathalielindqvist commented
> Hmm seems like the 'show' prop only shows it initially - if you hover in and out of it it closes. I don't think thats expected behavior, prolly needs a ticket

Yeah I noticed that too. Will write a ticket for it in Jira.

2023-07-05 09:00 UTC, mJarsater commented
> > Hmm seems like the 'show' prop only shows it initially - if you hover in and out of it it closes. I don't think thats expected behavior, prolly needs a ticket
> 
> Yeah I noticed that too. Will write a ticket for it in Jira.

I think you could try and changing the value of the show prop based on hover. I think thats how it's inteded to be used.

2023-07-05 09:01 UTC, mJarsater commented on src/pages/FormPage.tsx
> +          </tds-tooltip>
```suggestion
          <tds-tooltip
            placement="right"
            mouse-over-tooltip="true"
            show={showTooltip}
          >
            <p className="tds-detail-05 tds-u-m0 tooltip-paragraph">
              This option is required in order to submit the form.
            </p>
          </tds-tooltip>
```

2023-07-05 09:04 UTC, mJarsater commented on src/pages/FormPage.tsx
> +                <tds-icon name="info" size="16px"></tds-icon>
```suggestion
                <tds-icon 
                  onMouseEnter={setShowTooltip(true)}
                  onMouseLeave={setShowTooltip(false)}
                  name="info" size="16px"></tds-icon>
```

2023-07-05 09:33 UTC, nathalielindqvist commented
'show' prop is not put into action properly in the component, writing ticket in Jira.

2023-07-05 11:17 UTC, merged