fix(modal): updating modal component
scania-digital-design-system/tegel-react-demo pull request #59
Opened 2023-05-16 15:07 UTC by theJohnnyMe

- The previous version of the modal component was having old (css) buttons. This PR updates it to use the latest version od component.

2023-05-16 15:22 UTC, alexandereneroth requested changes

2023-05-16 15:31 UTC, theJohnnyMe commented on react-cra/src/components/Modal.tsx
> +        <sdds-modal selector="#my-modal-button" show id="my-modal" size="lg" actions="static" prevent>
Hahaha, I just realized myself even before you dropped the comment - I noticed some upsetting behaviour :D 
Nice catch! Thanks for review ;)

2023-05-17 12:22 UTC, alexandereneroth approved these changes
Nice 👍

2023-06-07 12:28 UTC, theJohnnyMe commented
The moment I forgot what was this one about...

2023-06-07 13:40 UTC, closed without merging